version: "1"
services:
  config-server:
    container_name: config-server
    build:
      context: config-server
      dockerfile: Dockerfile
    command: ["java","-jar","config-server-0.0.1-SNAPSHOT.jar"]
    ports:
      - 8888:8888
